email:
  password: 123
  server: imap.gmail.com
  login: test_login
  subject_prefix: test_
  users:
    apriyma0@gmail.com: Антон Прийма

db:
  user: root
  password: 123
  host: 127.0.0.1
  port: 3306
  dbname: diploma

tester:
  scheme_path: /Applications/Racket v8.1/bin/racket
  tests:
    - type: 1
      input: (my-gcd 10 2)
      expected: 2
